name: conditioning
description: connect the world, combine the hope.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # -------settings
  intl: any
  #  firebase_core: ^2.2.0
  #  flutter_native_splash: ^2.2.15

  # ----------------------------auth
  #  phone_number: ^2.0.1
  #  firebase_auth: ^4.1.2
  #  google_sign_in: ^6.1.4
  #  sign_in_with_apple: ^5.0.0
  #  flutter_facebook_auth: ^5.0.6
  #  github: ^9.6.0

  # ----------------------------store
  #  uuid: ^3.0.6
  #  path: ^1.8.2
  #  path_provider: ^2.0.11
  #  path_provider_windows: ^2.1.3
  #  hive: ^2.2.3
  #  cloud_firestore: ^4.0.5

  # ----------------------------function
  #  audioplayers: ^5.1.0
  #  ffmpeg_kit_flutter: ^6.0.0
  #  youtube_downloader: ^0.0.6

  # ----------------------------ui
  # -------text
  #  google_fonts: ^5.1.0
  #  flutter_tex: ^4.0.3+4
  #  flutter_quill: ^7.4.0
  animated_text_kit: ^4.2.2

  # -------others
  #  cupertino_icons: ^1.0.2
  #  table_calendar: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #  build_runner: ^2.3.2
  #  json_serializable: ^6.5.4
  #  json_annotation: ^4.7.0
  #  freezed: ^2.2.1
  #  freezed_annotation: ^2.2.0
  #  copy_with_extension: ^5.0.0
  #  copy_with_extension_gen: ^5.0.0
  #  dev: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Yozai
      fonts:
        - asset: assets/font/Yozai-Bold.ttf
        - asset: assets/font/Yozai-Light.ttf
        - asset: assets/font/Yozai-Medium.ttf
        - asset: assets/font/Yozai-Regular.ttf
flutter_intl:
  enabled: true
